import type { Metadata } from "next";
import "./styles/globals.css";
import { Providers } from "@/components/Store/Provider";
import Header from "@/components/UI/Header";
import Footer from "@/components/UI/Footer";

export const metadata: Metadata = {
  title: "Cloud Kitchen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased lg:hidden md:block">
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
